[project]
name = "scikit-learn-training"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "scikit-learn",
    "pandas",
    "polars",
    "seaborn",
    "matplotlib",
    "plotly",
    "notebook>=7.4.4",
    "pyarrow>=21.0.0",
    "imbalanced-learn>=0.14.0",
    "great-tables>=0.18.0",
    "altair>=5.5.0",
    "tensorflow>=2.20.0",
    "statsmodels>=0.14.5",
]
